### ISSUE TITLE
Minecraft server with version 1.20.2 and get this error

### ISSUE THREAD

**Issue by TSNCM** [kous500/CurveBuilding#15]
Plugin version: CurveBuilding 0.5.0
Server version: Paper-291 (MC: 1.20.2)

[09:43:23 INFO]: TSNCM issued server command: //pos set 1
[09:43:23 WARN]: Exception in thread "Timer-0" java.lang.NullPointerException: Cannot read field "DUST" because "me.kous500.curvebuilding.bukkit.CurveBuildingPlugin.particles_1_13" is null
[09:43:23 WARN]: 	at CurveBuilding.jar//me.kous500.curvebuilding.bukkit.SendParticles.sendCube(SendParticles.java:128)
[09:43:23 WARN]: 	at CurveBuilding.jar//me.kous500.curvebuilding.bukkit.SendParticles.sendParticlePlayer(SendParticles.java:89)
[09:43:23 WARN]: 	at CurveBuilding.jar//me.kous500.curvebuilding.bukkit.SendParticles.send(SendParticles.java:63)
[09:43:23 WARN]: 	at CurveBuilding.jar//me.kous500.curvebuilding.bukkit.SendParticles.run(SendParticles.java:55)
[09:43:23 WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[09:43:23 WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)

**Comment by tsingyayin** [comment]
Plugin version: CurveBuilding 0.5.0
Server version: Purpur-1.20.2-2082
Env: Windows Server 2022 + JDK 21.0

[20:34:05 WARN]: Exception in thread "Timer-2" java.lang.NullPointerException: Cannot read field "DUST" because "me.kous500.curvebuilding.bukkit.CurveBuildingPlugin.particles_1_13" is null
[20:34:05 WARN]:        at curvebuilding-bukkit-0.5.0.jar//me.kous500.curvebuilding.bukkit.SendParticles.sendCube(SendParticles.java:128)
[20:34:05 WARN]:        at curvebuilding-bukkit-0.5.0.jar//me.kous500.curvebuilding.bukkit.SendParticles.sendParticlePlayer(SendParticles.java:89)
[20:34:05 WARN]:        at curvebuilding-bukkit-0.5.0.jar//me.kous500.curvebuilding.bukkit.SendParticles.send(SendParticles.java:63)
[20:34:05 WARN]:        at curvebuilding-bukkit-0.5.0.jar//me.kous500.curvebuilding.bukkit.SendParticles.run(SendParticles.java:55)
[20:34:05 WARN]:        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[20:34:05 WARN]:        at java.base/java.util.TimerThread.run(Timer.java:516)

**Comment by tsingyayin** [comment]
Seems that there are some problems occured by particlenativeapi

**Comment by wacch** [comment]
Fixed in https://github.com/kous500/CurveBuilding/pull/16
