### ISSUE TITLE
Please support 1.21.3 & 1.21.4

### ISSUE THREAD

**Issue by tsingyayin** [kous500/CurveBuilding#38]
```
[00:09:33 WARN]: Exception in thread "Timer-2" java.lang.NullPointerException: Cannot read field "DUST" because "me.kous500.curvebuilding.bukkit.CurveBuildingPlugin.particles_1_13" is null
[00:09:33 WARN]:        at curvebuilding-bukkit-0.6.2.jar//me.kous500.curvebuilding.bukkit.SendParticles.sendCross(SendParticles.java:160)
[00:09:33 WARN]:        at curvebuilding-bukkit-0.6.2.jar//me.kous500.curvebuilding.bukkit.SendParticles.sendParticlePlayer(SendParticles.java:88)
[00:09:33 WARN]:        at curvebuilding-bukkit-0.6.2.jar//me.kous500.curvebuilding.bukkit.SendParticles.send(SendParticles.java:62)
[00:09:33 WARN]:        at curvebuilding-bukkit-0.6.2.jar//me.kous500.curvebuilding.bukkit.SendParticles.run(SendParticles.java:54)
[00:09:33 WARN]:        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[00:09:33 WARN]:        at java.base/java.util.TimerThread.run(Timer.java:516)
```
It seems that the plugin is not working very well in the new version

**Comment by tsingyayin** [comment]
And, can the Spigot version of this plugin be designed to not require frequent updates? Is there an implementation that allows users to continuously use this plugin by simply updating the Worldedit and Spigot servers?

**Comment by wacch** [comment]
No, and no plans for improvement.
If you have any suggestions for improvement, we would be glad to cooperate by submitting a PR.

**Comment by wacch** [comment]
fixed https://github.com/kous500/CurveBuilding/pull/39
